extends Node

const id = "TeaLovingLad.NOOB"

onready var Lure = get_node("/root/SulayreLure")

func _ready():
		Lure.add_content(id, "batty1_nose", "mod://Resources/Cosmetics/batty1_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "batty2_nose", "mod://Resources/Cosmetics/batty2_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "bulky1_nose", "mod://Resources/Cosmetics/bulky1_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "bulky2_nose", "mod://Resources/Cosmetics/bulky2_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "bulky3_nose", "mod://Resources/Cosmetics/bulky3_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "bulky4_nose", "mod://Resources/Cosmetics/bulky4_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "bulky5_nose", "mod://Resources/Cosmetics/bulky5_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "bulky6_nose", "mod://Resources/Cosmetics/bulky6_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "bulky7_nose", "mod://Resources/Cosmetics/bulky7_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "bulky8_nose", "mod://Resources/Cosmetics/bulky8_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "bulky9_nose", "mod://Resources/Cosmetics/bulky9_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "bulky10_nose", "mod://Resources/Cosmetics/bulky10_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "bulky11_nose", "mod://Resources/Cosmetics/bulky11_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "burst_nose", "mod://Resources/Cosmetics/burst_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "clueful_nose", "mod://Resources/Cosmetics/clueful_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "clueful_drab_nose", "mod://Resources/Cosmetics/clueful_drab_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "cut_nose", "mod://Resources/Cosmetics/cut_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "dotty_nose", "mod://Resources/Cosmetics/dotty_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "exhaust_nose", "mod://Resources/Cosmetics/exhaust_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "misplaced_nose", "mod://Resources/Cosmetics/misplaced_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "nosemoji_nose", "mod://Resources/Cosmetics/nosemoji_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "nosemoji_drab_nose", "mod://Resources/Cosmetics/nosemoji_drab_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "nostrils1_nose", "mod://Resources/Cosmetics/nostrils1_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "nostrils2_nose", "mod://Resources/Cosmetics/nostrils2_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "nostrils3_nose", "mod://Resources/Cosmetics/nostrils3_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "nostrils4_nose", "mod://Resources/Cosmetics/nostrils4_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "nostrils5_nose", "mod://Resources/Cosmetics/nostrils5_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "nostrils6_nose", "mod://Resources/Cosmetics/nostrils6_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "nostrils7_nose", "mod://Resources/Cosmetics/nostrils7_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "nostrils8_nose", "mod://Resources/Cosmetics/nostrils8_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "nostrils9_nose", "mod://Resources/Cosmetics/nostrils9_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "pierced_nose", "mod://Resources/Cosmetics/pierced_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "pointed1_nose", "mod://Resources/Cosmetics/pointed1_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "pointed2_nose", "mod://Resources/Cosmetics/pointed2_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "pointed3_nose", "mod://Resources/Cosmetics/pointed3_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "pointed4_nose", "mod://Resources/Cosmetics/pointed4_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "pointed5_nose", "mod://Resources/Cosmetics/pointed5_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "schnoslet_nose", "mod://Resources/Cosmetics/schnoslet_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "senseless_nose", "mod://Resources/Cosmetics/senseless_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "slim1_nose", "mod://Resources/Cosmetics/slim1_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "slim2_nose", "mod://Resources/Cosmetics/slim2_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "slim3_nose", "mod://Resources/Cosmetics/slim3_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "slim4_nose", "mod://Resources/Cosmetics/slim4_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "sniff_nose", "mod://Resources/Cosmetics/sniff_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "snout_nose", "mod://Resources/Cosmetics/snout_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "stache_nose", "mod://Resources/Cosmetics/stache_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "sticky_nose", "mod://Resources/Cosmetics/sticky_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "threepoint1_nose", "mod://Resources/Cosmetics/threepoint1_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "threepoint2_nose", "mod://Resources/Cosmetics/threepoint2_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "threepoint3_nose", "mod://Resources/Cosmetics/threepoint3_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "threepoint4_nose", "mod://Resources/Cosmetics/threepoint4_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "warped_nose", "mod://Resources/Cosmetics/warped_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
		Lure.add_content(id, "whisk_nose", "mod://Resources/Cosmetics/whisk_nose.tres", [Lure.FLAGS.FREE_UNLOCK])
